language: go

os:
  - linux
  - osx
  - windows

go:
  - 1.14.x
  - 1.13.x
  - 1.12.x
  - 1.11.x
  - 1.10.x
  - 1.9.x
  - 1.8.x
  - 1.7.x
  - tip

before_script:
  - go get -t -v ./...

script:
  - go test -v -cover -race ./...

jobs:
  allow_failures:
    - go: tip

  include:
    - stage: lint
      script:
        - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0
        - golangci-lint run

    - stage: cross compilation
      script:
        - GOOS=linux go build
        - GOOS=darwin go build
        - GOOS=freebsd go build
        - GOOS=windows go build
        - GOARCH=386 go build
