language: go
sudo: false
go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - tip

os:
  - linux
  - osx

script:
    # build test for supported platforms
  - GOOS=linux go build
  - GOOS=darwin go build
  - GOOS=freebsd go build
  - GOOS=windows go build
  - GOARCH=386 go build

  # run tests on a standard platform
  - go test -v ./...

  # run tests with the race detector as well
  - go test -race -v ./...
