name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0
