name: Test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version:
          - 1.21.x
          - 1.22.x
          - 1.23.x
          - 1.24.x
          - 1.25.x
        os: [ubuntu-latest, macos-latest, windows-latest, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - run: go version
      - run: go test -v -cover -shuffle=on ./...
      - run: go test -v -cover -shuffle=on -race ./...
